replicaCount: 2

image:
  repository: nginx
  tag: 1.25.3
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

